- id: update-modified
  name: "Update front matter to match sysmod stamp"
  description: "https://gist.github.com/welpo/6594765f5640982cb5886c9e9459ef5b"
  pass_filenames: false
  always_run: true
  language: system
  entry: update-modified.sh
